version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=${NODE_ENV}
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=mongodb://mongo:27017/TodoApp
    restart: always
    networks:
      - express-mongo
      - react-express
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.0
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo

networks:
  react-express:
  express-mongo:

volumes:
  mongo_data:
